/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3e4942',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#6e7a71',
        'outline-variant': '#bdcabf',
        'surface-tint': '#006c45',
        primary: '#006a43',
        'on-primary': '#ffffff',
        'primary-container': '#008656',
        'on-primary-container': '#f6fff6',
        'inverse-primary': '#71dba3',
        secondary: '#206a55',
        'on-secondary': '#ffffff',
        'secondary-container': '#a6eed3',
        'on-secondary-container': '#256e59',
        tertiary: '#555e5c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6d7674',
        'on-tertiary-container': '#f5fefb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#8df8be',
        'primary-fixed-dim': '#71dba3',
        'on-primary-fixed': '#002112',
        'on-primary-fixed-variant': '#005233',
        'secondary-fixed': '#a9f1d6',
        'secondary-fixed-dim': '#8dd5ba',
        'on-secondary-fixed': '#002117',
        'on-secondary-fixed-variant': '#00513e',
        'tertiary-fixed': '#dbe4e2',
        'tertiary-fixed-dim': '#bfc8c6',
        'on-tertiary-fixed': '#151d1c',
        'on-tertiary-fixed-variant': '#404947',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        mint: '#2E9E6C',
        teal: '#84CBB1',
        'water-green': '#F0F9F6',
        amber: '#f5a524',
      },
      fontFamily: {
        display: ['Quicksand', 'sans-serif'],
        body: ['Quicksand', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        card: '20px',
      },
      boxShadow: {
        ambient: '0 8px 30px -8px rgba(46, 158, 108, 0.18)',
        soft: '0 2px 12px -2px rgba(11, 28, 48, 0.06)',
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
}
